server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              -  "http://www.muzinsa.store.s3-website.ap-northeast-2.amazonaws.com"
              - "http://muzinsa.store.s3-website.ap-northeast-2.amazonaws.com"
              - "http://review-service-0124.s3-website.ap-northeast-2.amazonaws.com"
              - "https://www.muzinsa.store"
              - "http://www.muzinsa.store"
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          # k8s 클러스터 내에서 다른 서비스를 지목하기위한 DNS 명명 규칙.
          # <service-name>.<namespace>.svc.cluster.local:port
#          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter


        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
#          uri: http://restaurant-service.default.svc.cluster.local:8083
          predicates:
            - Path=/restaurant-service/**
          filters:
            - AuthorizationHeaderFilter

        - id: review-service
          uri: lb://REVIEW-SERVICE
#          uri: http://review-service.default.svc.cluster.local:8082
          predicates:
            - Path=/review-service/**
          filters:
            - AuthorizationHeaderFilter


        - id: point-service-api
          uri: lb://POINT-SERVICE
#          uri: http://point-service.default.svc.cluster.local:8084
          predicates:
            - Path=/point-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/point-service/(?<segment>.*), /$\{segment}

        - id: badge-api
          uri: lb://POINT-SERVICE
#          uri: http://point-service.default.svc.cluster.local:8084
          predicates:
            - Path=/badges/**
          filters:
            - AuthorizationHeaderFilter