server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant-service/**
          filters:
            - AuthorizationHeaderFilter

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - AuthorizationHeaderFilter


        - id: point-service-api
          uri: lb://POINT-SERVICE
          predicates:
            - Path=/point-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/point-service/(?<segment>.*), /$\{segment}

        - id: badge-api
          uri: lb://POINT-SERVICE
          predicates:
            - Path=/badges/**
          filters:
            - AuthorizationHeaderFilter